version: '3.1'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: scalereal
      MYSQL_DATABASE: scalereal
    ports:
            - "8000:8000"
    volumes:
            - ./data.sql:/data.sql
